package-lock.json
src/__tests__/check_export.test.ts
src/__tests__/renderers/iris_doc_renderer.test.ts
src/index.ts
src/renderers/iris_doc_renderer.ts

Implement the `IrisDocRenderer` to run the https://github.com/littleGnAl/iris-doc as a renderer.

feat: Implement the IrisDocRenderer

---

src/index.ts
src/parsers/pointer_marker_parser.ts
src/utils/obj_utils.ts

Add PointerMarkerParser to explicitly mark the pointer type
1. Pointer array
2. Just a pointer

feat: Add PointerMarkerParser

---

headers/rtc_4.3.0/custom_headers/CustomIAgoraRtcEngine.h

feat: rename startPreview to startPreviewWithoutSourceType

adapt native rtc sdk 4.3.0

---

src/index.ts
src/utils/obj_utils.ts

- Fix checkObjInclude not correct for array
- Export `obj_utils `

fix: Fix checkObjInclude not correct for array

---

src/__tests__/utils/iris_utils.test.ts
src/parsers/iris_api_id_parser.ts
src/parsers/merge_node_parser.ts
src/utils/iris_utils.ts

- Only hash for the parameter list for irisApiId
- Use sha1 to calculate the hash

Only hash for the parameter list for irisApiId

---

.github/workflows/update_headers.yml
scripts/update_headers.sh

usage: https://github.com/AgoraIO-Extensions/terra_shared_configs/actions/workflows/update_headers.yml
example: https://github.com/AgoraIO-Extensions/terra_shared_configs/pull/59

ci: upload native sdk file

---

headers/rtc_4.3.1/include/AgoraMediaBase.h
headers/rtc_4.3.1/include/IAgoraRtcEngine.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.1_headers.zip

[AUTO] Update native headers

---

src/__tests__/parsers/cud_node_parser.test.ts
src/parsers/cud_node_parser.ts
src/parsers/index.ts

Add a common parser to handle the Create/Update/Delete operations on the nodes.

feat: [CUDNodeParser] Add a common parser to handle the Create/Update/Delete operations on the nodes

---

src/__tests__/renderers/iris_doc_renderer.test.ts
src/renderers/iris_doc_renderer.ts

Fix `python3 -m pip install xxx` error `error: externally-managed-environment`

fix: [iris_doc_renderer] Run python3 inside venv

---

src/__tests__/renderers/iris_doc_renderer.test.ts
src/renderers/iris_doc_renderer.ts

`source` not found on Linux, should use `.`

fix: [iris_doc_renderer] Fix can not run on linux

---

headers/rtc_4.3.2.1/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.1/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.1/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.1/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.1/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.1/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.1/include/AgoraBase.h
headers/rtc_4.3.2.1/include/AgoraMediaBase.h
headers/rtc_4.3.2.1/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.1/include/AgoraOptional.h
headers/rtc_4.3.2.1/include/AgoraRefPtr.h
headers/rtc_4.3.2.1/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.1/include/IAgoraLog.h
headers/rtc_4.3.2.1/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.1/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.1/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.1/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.1/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.1/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.1/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.1/include/IAgoraParameter.h
headers/rtc_4.3.2.1/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.1/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.1/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.1/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.1/include/IAudioDeviceManager.h
headers/rtc_4.3.2.1/include/time_utils.h
headers/rtc_4.3.2.1/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.1_headers.zip

[AUTO] Update native headers to 4.3.2.1

---

.github/workflows/update_headers.yml
headers/rtc_4.2.6.15/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.15/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.15/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.15/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.15/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.15/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.15/include/AgoraBase.h
headers/rtc_4.2.6.15/include/AgoraMediaBase.h
headers/rtc_4.2.6.15/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.15/include/AgoraOptional.h
headers/rtc_4.2.6.15/include/AgoraRefPtr.h
headers/rtc_4.2.6.15/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.15/include/IAgoraLog.h
headers/rtc_4.2.6.15/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.15/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.15/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.15/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.15/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.15/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.15/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.15/include/IAgoraParameter.h
headers/rtc_4.2.6.15/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.15/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.15/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.15/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.15/include/IAudioDeviceManager.h
headers/rtc_4.2.6.15/include/time_utils.h
headers/rtc_4.2.6.15/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.15_25607_FULL_20240709_1059_318143.zip

[AUTO] Update native headers to 4.2.6.15

---

.github/workflows/update_headers.yml
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.15_lite/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.15_lite/include/AgoraBase.h
headers/rtc_4.2.6.15_lite/include/AgoraMediaBase.h
headers/rtc_4.2.6.15_lite/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.15_lite/include/AgoraOptional.h
headers/rtc_4.2.6.15_lite/include/AgoraRefPtr.h
headers/rtc_4.2.6.15_lite/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.15_lite/include/IAgoraLog.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.15_lite/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.15_lite/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.15_lite/include/IAgoraParameter.h
headers/rtc_4.2.6.15_lite/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.15_lite/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.15_lite/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.15_lite/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.15_lite/include/IAudioDeviceManager.h
headers/rtc_4.2.6.15_lite/include/time_utils.h
headers/rtc_4.2.6.15_lite/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.15_25607_FULL_20240709_1059_318143.zip

[AUTO] Update native headers to 4.2.6.15_lite

---

headers/rtc_4.3.2.2/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.2/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.2/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.2/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.2/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.2/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.2/include/AgoraBase.h
headers/rtc_4.3.2.2/include/AgoraMediaBase.h
headers/rtc_4.3.2.2/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.2/include/AgoraOptional.h
headers/rtc_4.3.2.2/include/AgoraRefPtr.h
headers/rtc_4.3.2.2/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.2/include/IAgoraLog.h
headers/rtc_4.3.2.2/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.2/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.2/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.2/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.2/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.2/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.2/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.2/include/IAgoraParameter.h
headers/rtc_4.3.2.2/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.2/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.2/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.2/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.2/include/IAudioDeviceManager.h
headers/rtc_4.3.2.2/include/time_utils.h
headers/rtc_4.3.2.2/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.2_headers.zip

[AUTO] Update native headers to 4.3.2.2

---

headers/rtc_4.3.2.2_pip/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.2_pip/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.2_pip/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.2_pip/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.2_pip/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.2_pip/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.2_pip/include/AgoraBase.h
headers/rtc_4.3.2.2_pip/include/AgoraMediaBase.h
headers/rtc_4.3.2.2_pip/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.2_pip/include/AgoraOptional.h
headers/rtc_4.3.2.2_pip/include/AgoraRefPtr.h
headers/rtc_4.3.2.2_pip/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.2_pip/include/IAgoraLog.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.2_pip/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.2_pip/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.2_pip/include/IAgoraParameter.h
headers/rtc_4.3.2.2_pip/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.2_pip/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.2_pip/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.2_pip/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.2_pip/include/IAudioDeviceManager.h
headers/rtc_4.3.2.2_pip/include/time_utils.h
headers/rtc_4.3.2.2_pip/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.2_pip_headers.zip

[AUTO] Update native headers to 4.3.2.2_pip

---

headers/rtc_4.3.1.136/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.1.136/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.1.136/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.1.136/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.1.136/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.1.136/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.1.136/include/AgoraBase.h
headers/rtc_4.3.1.136/include/AgoraMediaBase.h
headers/rtc_4.3.1.136/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.1.136/include/AgoraOptional.h
headers/rtc_4.3.1.136/include/AgoraRefPtr.h
headers/rtc_4.3.1.136/include/IAgoraH265Transcoder.h
headers/rtc_4.3.1.136/include/IAgoraLog.h
headers/rtc_4.3.1.136/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.1.136/include/IAgoraMediaEngine.h
headers/rtc_4.3.1.136/include/IAgoraMediaPlayer.h
headers/rtc_4.3.1.136/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.1.136/include/IAgoraMediaRecorder.h
headers/rtc_4.3.1.136/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.1.136/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.1.136/include/IAgoraParameter.h
headers/rtc_4.3.1.136/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.1.136/include/IAgoraRtcEngine.h
headers/rtc_4.3.1.136/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.1.136/include/IAgoraSpatialAudio.h
headers/rtc_4.3.1.136/include/IAudioDeviceManager.h
headers/rtc_4.3.1.136/include/time_utils.h
headers/rtc_4.3.1.136/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.1.136_headers.zip

[AUTO] Update native headers to 4.3.1.136

---

headers/rtc_4.2.6.142/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.142/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.142/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.142/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.142/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.142/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.142/include/AgoraBase.h
headers/rtc_4.2.6.142/include/AgoraMediaBase.h
headers/rtc_4.2.6.142/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.142/include/AgoraOptional.h
headers/rtc_4.2.6.142/include/AgoraRefPtr.h
headers/rtc_4.2.6.142/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.142/include/IAgoraLog.h
headers/rtc_4.2.6.142/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.142/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.142/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.142/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.142/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.142/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.142/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.142/include/IAgoraParameter.h
headers/rtc_4.2.6.142/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.142/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.142/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.142/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.142/include/IAudioDeviceManager.h
headers/rtc_4.2.6.142/include/time_utils.h
headers/rtc_4.2.6.142/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.142_26014_FULL_20240807_1912_326094.zip

[AUTO] Update native headers to 4.2.6.142

---

headers/rtc_4.2.6.16/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.16/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.16/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.16/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.16/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.16/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.16/include/AgoraBase.h
headers/rtc_4.2.6.16/include/AgoraMediaBase.h
headers/rtc_4.2.6.16/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.16/include/AgoraOptional.h
headers/rtc_4.2.6.16/include/AgoraRefPtr.h
headers/rtc_4.2.6.16/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.16/include/IAgoraLog.h
headers/rtc_4.2.6.16/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.16/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.16/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.16/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.16/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.16/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.16/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.16/include/IAgoraParameter.h
headers/rtc_4.2.6.16/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.16/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.16/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.16/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.16/include/IAudioDeviceManager.h
headers/rtc_4.2.6.16/include/time_utils.h
headers/rtc_4.2.6.16/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.16_headers.zip

[AUTO] Update native headers to 4.2.6.16

---

headers/rtc_4.3.2.4/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.4/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.4/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.4/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.4/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.4/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.4/include/AgoraBase.h
headers/rtc_4.3.2.4/include/AgoraMediaBase.h
headers/rtc_4.3.2.4/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.4/include/AgoraOptional.h
headers/rtc_4.3.2.4/include/AgoraRefPtr.h
headers/rtc_4.3.2.4/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.4/include/IAgoraLog.h
headers/rtc_4.3.2.4/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.4/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.4/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.4/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.4/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.4/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.4/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.4/include/IAgoraParameter.h
headers/rtc_4.3.2.4/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.4/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.4/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.4/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.4/include/IAudioDeviceManager.h
headers/rtc_4.3.2.4/include/time_utils.h
headers/rtc_4.3.2.4/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.4_headers.zip

[AUTO] Update native headers to 4.3.2.4

---

headers/rtc_4.2.6.17/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.17/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.17/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.17/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.17/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.17/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.17/include/AgoraBase.h
headers/rtc_4.2.6.17/include/AgoraMediaBase.h
headers/rtc_4.2.6.17/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.17/include/AgoraOptional.h
headers/rtc_4.2.6.17/include/AgoraRefPtr.h
headers/rtc_4.2.6.17/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.17/include/IAgoraLog.h
headers/rtc_4.2.6.17/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.17/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.17/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.17/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.17/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.17/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.17/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.17/include/IAgoraParameter.h
headers/rtc_4.2.6.17/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.17/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.17/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.17/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.17/include/IAudioDeviceManager.h
headers/rtc_4.2.6.17/include/time_utils.h
headers/rtc_4.2.6.17/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.17_26106_FULL_20240815_1946_328392.zip

[AUTO] Update native headers to 4.2.6.17

---

headers/rtc_4.2.6.126/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.126/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.126/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.126/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.126/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.126/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.126/include/AgoraBase.h
headers/rtc_4.2.6.126/include/AgoraMediaBase.h
headers/rtc_4.2.6.126/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.126/include/AgoraOptional.h
headers/rtc_4.2.6.126/include/AgoraRefPtr.h
headers/rtc_4.2.6.126/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.126/include/IAgoraLog.h
headers/rtc_4.2.6.126/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.126/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.126/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.126/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.126/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.126/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.126/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.126/include/IAgoraParameter.h
headers/rtc_4.2.6.126/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.126/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.126/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.126/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.126/include/IAudioDeviceManager.h
headers/rtc_4.2.6.126/include/time_utils.h
headers/rtc_4.2.6.126/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.126_26180_FULL_20240821_1819_329758.zip

[AUTO] Update native headers to 4.2.6.126

---

headers/rtc_4.2.6.127/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.127/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.127/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.127/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.127/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.127/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.127/include/AgoraBase.h
headers/rtc_4.2.6.127/include/AgoraMediaBase.h
headers/rtc_4.2.6.127/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.127/include/AgoraOptional.h
headers/rtc_4.2.6.127/include/AgoraRefPtr.h
headers/rtc_4.2.6.127/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.127/include/IAgoraLog.h
headers/rtc_4.2.6.127/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.127/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.127/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.127/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.127/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.127/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.127/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.127/include/IAgoraParameter.h
headers/rtc_4.2.6.127/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.127/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.127/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.127/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.127/include/IAudioDeviceManager.h
headers/rtc_4.2.6.127/include/time_utils.h
headers/rtc_4.2.6.127/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.127_headers.zip

[AUTO] Update native headers to 4.2.6.127

---

headers/rtc_4.3.2.5/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.5/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.5/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.5/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.5/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.5/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.5/include/AgoraBase.h
headers/rtc_4.3.2.5/include/AgoraMediaBase.h
headers/rtc_4.3.2.5/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.5/include/AgoraOptional.h
headers/rtc_4.3.2.5/include/AgoraRefPtr.h
headers/rtc_4.3.2.5/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.5/include/IAgoraLog.h
headers/rtc_4.3.2.5/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.5/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.5/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.5/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.5/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.5/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.5/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.5/include/IAgoraParameter.h
headers/rtc_4.3.2.5/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.5/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.5/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.5/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.5/include/IAudioDeviceManager.h
headers/rtc_4.3.2.5/include/time_utils.h
headers/rtc_4.3.2.5/shared_configs.yaml

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.5_headers.zip

[AUTO] Update native headers to 4.3.2.5

---

headers/rtc_4.2.6.18/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.18/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.18/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.18/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.18/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.18/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.18/include/AgoraBase.h
headers/rtc_4.2.6.18/include/AgoraMediaBase.h
headers/rtc_4.2.6.18/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.18/include/AgoraOptional.h
headers/rtc_4.2.6.18/include/AgoraRefPtr.h
headers/rtc_4.2.6.18/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.18/include/IAgoraLog.h
headers/rtc_4.2.6.18/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.18/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.18/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.18/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.18/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.18/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.18/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.18/include/IAgoraParameter.h
headers/rtc_4.2.6.18/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.18/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.18/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.18/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.18/include/IAudioDeviceManager.h
headers/rtc_4.2.6.18/include/time_utils.h
headers/rtc_4.2.6.18/shared_configs.yaml

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.18_26433_FULL_20240909_1657_334470.zip

[AUTO] Update native headers to 4.2.6.18

---

headers/rtc_4.5.0/include/AgoraBase.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_arsenal_headers.zip

[AUTO] Update native headers to 4.5.0

---

headers/rtc_4.2.6.19/include/AgoraBase.h
headers/rtc_4.2.6.19/include/AgoraMediaBase.h
headers/rtc_4.2.6.19/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.19/include/AgoraOptional.h
headers/rtc_4.2.6.19/include/AgoraRefPtr.h
headers/rtc_4.2.6.19/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.19/include/IAgoraLog.h
headers/rtc_4.2.6.19/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.19/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.19/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.19/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.19/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.19/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.19/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.19/include/IAgoraParameter.h
headers/rtc_4.2.6.19/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.19/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.19/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.19/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.19/include/IAudioDeviceManager.h
headers/rtc_4.2.6.19/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.19_26847_FULL_20241015_2119_384866.zip

[AUTO] Update native headers to rtc_4.2.6.19

---

headers/rtc_4.5.0/include/rte_base/c/c_player.h
headers/rtc_4.5.0/include/rte_base/rte_cpp_callback_utils.h
headers/rtc_4.5.0/include/rte_base/rte_cpp_canvas.h
headers/rtc_4.5.0/include/rte_base/rte_cpp_error.h
headers/rtc_4.5.0/include/rte_base/rte_cpp_player.h
headers/rtc_4.5.0/include/rte_base/rte_cpp_rte.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_arsenal_headers.zip

[AUTO] Update native headers to rtc_4.5.0

---

headers/rtc_4.3.1.201/include/AgoraBase.h
headers/rtc_4.3.1.201/include/AgoraMediaBase.h
headers/rtc_4.3.1.201/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.1.201/include/AgoraOptional.h
headers/rtc_4.3.1.201/include/AgoraRefPtr.h
headers/rtc_4.3.1.201/include/IAgoraH265Transcoder.h
headers/rtc_4.3.1.201/include/IAgoraLog.h
headers/rtc_4.3.1.201/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.1.201/include/IAgoraMediaEngine.h
headers/rtc_4.3.1.201/include/IAgoraMediaPlayer.h
headers/rtc_4.3.1.201/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.1.201/include/IAgoraMediaRecorder.h
headers/rtc_4.3.1.201/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.1.201/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.1.201/include/IAgoraParameter.h
headers/rtc_4.3.1.201/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.1.201/include/IAgoraRtcEngine.h
headers/rtc_4.3.1.201/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.1.201/include/IAgoraSpatialAudio.h
headers/rtc_4.3.1.201/include/IAudioDeviceManager.h
headers/rtc_4.3.1.201/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.1.201_headers.zip

[AUTO] Update native headers to rtc_4.3.1.201

---

headers/rtc_4.3.2.9/include/AgoraBase.h
headers/rtc_4.3.2.9/include/AgoraMediaBase.h
headers/rtc_4.3.2.9/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.9/include/AgoraOptional.h
headers/rtc_4.3.2.9/include/AgoraRefPtr.h
headers/rtc_4.3.2.9/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.9/include/IAgoraLog.h
headers/rtc_4.3.2.9/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.9/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.9/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.9/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.9/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.9/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.9/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.9/include/IAgoraParameter.h
headers/rtc_4.3.2.9/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.9/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.9/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.9/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.9/include/IAudioDeviceManager.h
headers/rtc_4.3.2.9/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.9_27193_FULL_20241118_1624_437681.zip

[AUTO] Update native headers to rtc_4.3.2.9

---

headers/rtc_4.3.2.10/include/AgoraBase.h
headers/rtc_4.3.2.10/include/AgoraMediaBase.h
headers/rtc_4.3.2.10/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.10/include/AgoraOptional.h
headers/rtc_4.3.2.10/include/AgoraRefPtr.h
headers/rtc_4.3.2.10/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.10/include/IAgoraLog.h
headers/rtc_4.3.2.10/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.10/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.10/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.10/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.10/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.10/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.10/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.10/include/IAgoraParameter.h
headers/rtc_4.3.2.10/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.10/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.10/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.10/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.10/include/IAudioDeviceManager.h
headers/rtc_4.3.2.10/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.10_27367_FULL_20241203_1629_461253.zip

[AUTO] Update native headers to rtc_4.3.2.10

---

headers/rtc_4.3.2.11/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.11/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.11/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.11/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.11/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.11/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.11/include/AgoraBase.h
headers/rtc_4.3.2.11/include/AgoraMediaBase.h
headers/rtc_4.3.2.11/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.11/include/AgoraOptional.h
headers/rtc_4.3.2.11/include/AgoraRefPtr.h
headers/rtc_4.3.2.11/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.11/include/IAgoraLog.h
headers/rtc_4.3.2.11/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.11/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.11/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.11/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.11/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.11/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.11/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.11/include/IAgoraParameter.h
headers/rtc_4.3.2.11/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.11/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.11/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.11/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.11/include/IAudioDeviceManager.h
headers/rtc_4.3.2.11/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.11_27381_FULL_20241205_1437_464296.zip

[AUTO] Update native headers to rtc_4.3.2.11

---

headers/rtc_4.2.6.20/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.20/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.20/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.20/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.20/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.20/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.20/include/AgoraBase.h
headers/rtc_4.2.6.20/include/AgoraMediaBase.h
headers/rtc_4.2.6.20/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.20/include/AgoraOptional.h
headers/rtc_4.2.6.20/include/AgoraRefPtr.h
headers/rtc_4.2.6.20/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.20/include/IAgoraLog.h
headers/rtc_4.2.6.20/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.20/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.20/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.20/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.20/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.20/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.20/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.20/include/IAgoraParameter.h
headers/rtc_4.2.6.20/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.20/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.20/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.20/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.20/include/IAudioDeviceManager.h
headers/rtc_4.2.6.20/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.4.1.5_headers.zip

[AUTO] Update native headers to rtc_4.2.6.20

---

headers/rtc_4.2.6.21/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.21/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.21/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.21/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.21/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.21/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.21/include/AgoraBase.h
headers/rtc_4.2.6.21/include/AgoraMediaBase.h
headers/rtc_4.2.6.21/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.21/include/AgoraOptional.h
headers/rtc_4.2.6.21/include/AgoraRefPtr.h
headers/rtc_4.2.6.21/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.21/include/IAgoraLog.h
headers/rtc_4.2.6.21/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.21/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.21/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.21/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.21/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.21/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.21/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.21/include/IAgoraParameter.h
headers/rtc_4.2.6.21/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.21/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.21/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.21/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.21/include/IAudioDeviceManager.h
headers/rtc_4.2.6.21/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.21_headers.zip

[AUTO] Update native headers to rtc_4.2.6.21

---

headers/rtc_4.2.6.153/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.153/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.153/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.153/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.153/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.153/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.153/include/AgoraBase.h
headers/rtc_4.2.6.153/include/AgoraMediaBase.h
headers/rtc_4.2.6.153/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.153/include/AgoraOptional.h
headers/rtc_4.2.6.153/include/AgoraRefPtr.h
headers/rtc_4.2.6.153/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.153/include/IAgoraLog.h
headers/rtc_4.2.6.153/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.153/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.153/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.153/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.153/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.153/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.153/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.153/include/IAgoraParameter.h
headers/rtc_4.2.6.153/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.153/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.153/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.153/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.153/include/IAudioDeviceManager.h
headers/rtc_4.2.6.153/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.153_27683_FULL_20241230_2024_503327.zip

[AUTO] Update native headers to rtc_4.2.6.153

---

headers/rtc_4.2.6.154/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.154/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.154/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.154/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.154/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.154/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.154/include/AgoraBase.h
headers/rtc_4.2.6.154/include/AgoraMediaBase.h
headers/rtc_4.2.6.154/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.154/include/AgoraOptional.h
headers/rtc_4.2.6.154/include/AgoraRefPtr.h
headers/rtc_4.2.6.154/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.154/include/IAgoraLog.h
headers/rtc_4.2.6.154/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.154/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.154/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.154/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.154/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.154/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.154/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.154/include/IAgoraParameter.h
headers/rtc_4.2.6.154/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.154/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.154/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.154/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.154/include/IAudioDeviceManager.h
headers/rtc_4.2.6.154/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.20_27477_FULL_20241214_1658_478403.zip

[AUTO] Update native headers to rtc_4.2.6.154

---

headers/rtc_4.2.6.152/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.152/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.152/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.152/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.152/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.152/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.152/include/AgoraBase.h
headers/rtc_4.2.6.152/include/AgoraMediaBase.h
headers/rtc_4.2.6.152/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.152/include/AgoraOptional.h
headers/rtc_4.2.6.152/include/AgoraRefPtr.h
headers/rtc_4.2.6.152/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.152/include/IAgoraLog.h
headers/rtc_4.2.6.152/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.152/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.152/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.152/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.152/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.152/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.152/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.152/include/IAgoraParameter.h
headers/rtc_4.2.6.152/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.152/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.152/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.152/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.152/include/IAudioDeviceManager.h
headers/rtc_4.2.6.152/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.152_28066_FULL_20250212_1519_568275.zip

[AUTO] Update native headers to rtc_4.2.6.152

---

headers/rtc_4.3.2.14/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.14/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.14/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.14/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.14/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.14/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.14/include/AgoraBase.h
headers/rtc_4.3.2.14/include/AgoraMediaBase.h
headers/rtc_4.3.2.14/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.14/include/AgoraOptional.h
headers/rtc_4.3.2.14/include/AgoraRefPtr.h
headers/rtc_4.3.2.14/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.14/include/IAgoraLog.h
headers/rtc_4.3.2.14/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.14/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.14/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.14/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.14/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.14/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.14/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.14/include/IAgoraParameter.h
headers/rtc_4.3.2.14/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.14/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.14/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.14/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.14/include/IAudioDeviceManager.h
headers/rtc_4.3.2.14/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.14_28226_FULL_20250227_1217_591128.zip

[AUTO] Update native headers to rtc_4.3.2.14

---

headers/rtm_2.2.3/custom_headers/CustomIAgoraRtmClient.h
headers/rtm_2.2.3/custom_headers/CustomIAgoraStreamChannel.h
headers/rtm_2.2.3/include/AgoraRtmBase.h
headers/rtm_2.2.3/include/IAgoraRtmClient.h
headers/rtm_2.2.3/include/IAgoraRtmHistory.h
headers/rtm_2.2.3/include/IAgoraRtmLock.h
headers/rtm_2.2.3/include/IAgoraRtmPresence.h
headers/rtm_2.2.3/include/IAgoraRtmStorage.h
headers/rtm_2.2.3/include/IAgoraStreamChannel.h

https://download.agora.io/rtm2/release/Agora_RTM_C%2B%2B_SDK_for_Windows_v2.2.3.zip

[AUTO] Update native headers to rtm_2.2.3

---

headers/rtc_4.2.6.157/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.157/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.157/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.157/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.157/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.157/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.157/include/AgoraBase.h
headers/rtc_4.2.6.157/include/AgoraMediaBase.h
headers/rtc_4.2.6.157/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.157/include/AgoraOptional.h
headers/rtc_4.2.6.157/include/AgoraRefPtr.h
headers/rtc_4.2.6.157/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.157/include/IAgoraLog.h
headers/rtc_4.2.6.157/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.157/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.157/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.157/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.157/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.157/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.157/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.157/include/IAgoraParameter.h
headers/rtc_4.2.6.157/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.157/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.157/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.157/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.157/include/IAudioDeviceManager.h
headers/rtc_4.2.6.157/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.157_28548_FULL_20250402_1648_640826.zip

[AUTO] Update native headers to rtc_4.2.6.157

---

headers/rtc_4.2.2.147/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.2.147/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.2.147/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.2.147/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.2.147/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.2.147/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.2.147/include/AgoraBase.h
headers/rtc_4.2.2.147/include/AgoraMediaBase.h
headers/rtc_4.2.2.147/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.2.147/include/AgoraOptional.h
headers/rtc_4.2.2.147/include/AgoraRefPtr.h
headers/rtc_4.2.2.147/include/IAgoraH265Transcoder.h
headers/rtc_4.2.2.147/include/IAgoraLog.h
headers/rtc_4.2.2.147/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.2.147/include/IAgoraMediaEngine.h
headers/rtc_4.2.2.147/include/IAgoraMediaPlayer.h
headers/rtc_4.2.2.147/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.2.147/include/IAgoraMediaRecorder.h
headers/rtc_4.2.2.147/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.2.147/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.2.147/include/IAgoraParameter.h
headers/rtc_4.2.2.147/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.2.147/include/IAgoraRtcEngine.h
headers/rtc_4.2.2.147/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.2.147/include/IAgoraSpatialAudio.h
headers/rtc_4.2.2.147/include/IAudioDeviceManager.h
headers/rtc_4.2.2.147/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.2.147_28750_FULL_20250424_1055_673818.zip

[AUTO] Update native headers to rtc_4.2.2.147

---

headers/rtc_4.1.2.152/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.1.2.152/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.1.2.152/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.1.2.152/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.1.2.152/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.1.2.152/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.1.2.152/include/AgoraBase.h
headers/rtc_4.1.2.152/include/AgoraMediaBase.h
headers/rtc_4.1.2.152/include/AgoraMediaPlayerTypes.h
headers/rtc_4.1.2.152/include/AgoraOptional.h
headers/rtc_4.1.2.152/include/AgoraRefPtr.h
headers/rtc_4.1.2.152/include/IAgoraLog.h
headers/rtc_4.1.2.152/include/IAgoraMediaComponentFactory.h
headers/rtc_4.1.2.152/include/IAgoraMediaEngine.h
headers/rtc_4.1.2.152/include/IAgoraMediaPlayer.h
headers/rtc_4.1.2.152/include/IAgoraMediaPlayerSource.h
headers/rtc_4.1.2.152/include/IAgoraMediaRecorder.h
headers/rtc_4.1.2.152/include/IAgoraMediaStreamingSource.h
headers/rtc_4.1.2.152/include/IAgoraMusicContentCenter.h
headers/rtc_4.1.2.152/include/IAgoraParameter.h
headers/rtc_4.1.2.152/include/IAgoraRhythmPlayer.h
headers/rtc_4.1.2.152/include/IAgoraRtcEngine.h
headers/rtc_4.1.2.152/include/IAgoraRtcEngineEx.h
headers/rtc_4.1.2.152/include/IAgoraSpatialAudio.h
headers/rtc_4.1.2.152/include/IAudioDeviceManager.h
headers/rtc_4.1.2.152/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.1.2.152_28820_FULL_20250428_1932_680644.zip

[AUTO] Update native headers to rtc_4.1.2.152

---

headers/rtm_2.2.4/custom_headers/CustomIAgoraRtmClient.h
headers/rtm_2.2.4/custom_headers/CustomIAgoraStreamChannel.h
headers/rtm_2.2.4/include/AgoraRtmBase.h
headers/rtm_2.2.4/include/IAgoraRtmClient.h
headers/rtm_2.2.4/include/IAgoraRtmHistory.h
headers/rtm_2.2.4/include/IAgoraRtmLock.h
headers/rtm_2.2.4/include/IAgoraRtmPresence.h
headers/rtm_2.2.4/include/IAgoraRtmStorage.h
headers/rtm_2.2.4/include/IAgoraStreamChannel.h

https://download.agora.io/rtm2/release/Agora_RTM_C%2B%2B_SDK_for_Windows_v2.2.4.zip

[AUTO] Update native headers to rtm_2.2.4

---

headers/rtc_4.3.2.4421/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.4421/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.4421/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.4421/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.4421/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.4421/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.4421/include/AgoraBase.h
headers/rtc_4.3.2.4421/include/AgoraMediaBase.h
headers/rtc_4.3.2.4421/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.4421/include/AgoraOptional.h
headers/rtc_4.3.2.4421/include/AgoraRefPtr.h
headers/rtc_4.3.2.4421/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.4421/include/IAgoraLog.h
headers/rtc_4.3.2.4421/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.4421/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.4421/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.4421/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.4421/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.4421/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.4421/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.4421/include/IAgoraParameter.h
headers/rtc_4.3.2.4421/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.4421/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.4421/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.4421/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.4421/include/IAudioDeviceManager.h
headers/rtc_4.3.2.4421/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.4421_headers.zip

[AUTO] Update native headers to rtc_4.3.2.4421

---

headers/rtc_4.3.2.16/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.16/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.16/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.16/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.16/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.16/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.16/include/AgoraBase.h
headers/rtc_4.3.2.16/include/AgoraMediaBase.h
headers/rtc_4.3.2.16/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.16/include/AgoraOptional.h
headers/rtc_4.3.2.16/include/AgoraRefPtr.h
headers/rtc_4.3.2.16/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.16/include/IAgoraLog.h
headers/rtc_4.3.2.16/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.16/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.16/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.16/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.16/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.16/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.16/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.16/include/IAgoraParameter.h
headers/rtc_4.3.2.16/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.16/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.16/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.16/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.16/include/IAudioDeviceManager.h
headers/rtc_4.3.2.16/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.3.2.16_headers.zip

[AUTO] Update native headers to rtc_4.3.2.16

---

headers/rtc_4.2.2.148/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.2.148/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.2.148/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.2.148/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.2.148/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.2.148/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.2.148/include/AgoraBase.h
headers/rtc_4.2.2.148/include/AgoraMediaBase.h
headers/rtc_4.2.2.148/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.2.148/include/AgoraOptional.h
headers/rtc_4.2.2.148/include/AgoraRefPtr.h
headers/rtc_4.2.2.148/include/IAgoraH265Transcoder.h
headers/rtc_4.2.2.148/include/IAgoraLog.h
headers/rtc_4.2.2.148/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.2.148/include/IAgoraMediaEngine.h
headers/rtc_4.2.2.148/include/IAgoraMediaPlayer.h
headers/rtc_4.2.2.148/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.2.148/include/IAgoraMediaRecorder.h
headers/rtc_4.2.2.148/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.2.148/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.2.148/include/IAgoraParameter.h
headers/rtc_4.2.2.148/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.2.148/include/IAgoraRtcEngine.h
headers/rtc_4.2.2.148/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.2.148/include/IAgoraSpatialAudio.h
headers/rtc_4.2.2.148/include/IAudioDeviceManager.h
headers/rtc_4.2.2.148/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.2.148_headers.zip

[AUTO] Update native headers to rtc_4.2.2.148

---

headers/rtc_4.2.6.163/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.163/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.163/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.163/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.163/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.163/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.163/include/AgoraBase.h
headers/rtc_4.2.6.163/include/AgoraMediaBase.h
headers/rtc_4.2.6.163/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.163/include/AgoraOptional.h
headers/rtc_4.2.6.163/include/AgoraRefPtr.h
headers/rtc_4.2.6.163/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.163/include/IAgoraLog.h
headers/rtc_4.2.6.163/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.163/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.163/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.163/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.163/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.163/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.163/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.163/include/IAgoraParameter.h
headers/rtc_4.2.6.163/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.163/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.163/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.163/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.163/include/IAudioDeviceManager.h
headers/rtc_4.2.6.163/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.163_headers.zip

[AUTO] Update native headers to rtc_4.2.6.163

---

headers/rtc_4.3.2.145/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.145/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.145/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.145/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.145/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.145/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.145/include/AgoraBase.h
headers/rtc_4.3.2.145/include/AgoraMediaBase.h
headers/rtc_4.3.2.145/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.145/include/AgoraOptional.h
headers/rtc_4.3.2.145/include/AgoraRefPtr.h
headers/rtc_4.3.2.145/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.145/include/IAgoraLog.h
headers/rtc_4.3.2.145/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.145/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.145/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.145/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.145/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.145/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.145/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.145/include/IAgoraParameter.h
headers/rtc_4.3.2.145/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.145/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.145/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.145/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.145/include/IAudioDeviceManager.h
headers/rtc_4.3.2.145/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.145_29158_FULL_20250609_1122_736863.zip

[AUTO] Update native headers to rtc_4.3.2.145

---

headers/rtc_4.2.2.149/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.2.149/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.2.149/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.2.149/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.2.149/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.2.149/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.2.149/include/AgoraBase.h
headers/rtc_4.2.2.149/include/AgoraMediaBase.h
headers/rtc_4.2.2.149/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.2.149/include/AgoraOptional.h
headers/rtc_4.2.2.149/include/AgoraRefPtr.h
headers/rtc_4.2.2.149/include/IAgoraH265Transcoder.h
headers/rtc_4.2.2.149/include/IAgoraLog.h
headers/rtc_4.2.2.149/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.2.149/include/IAgoraMediaEngine.h
headers/rtc_4.2.2.149/include/IAgoraMediaPlayer.h
headers/rtc_4.2.2.149/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.2.149/include/IAgoraMediaRecorder.h
headers/rtc_4.2.2.149/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.2.149/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.2.149/include/IAgoraParameter.h
headers/rtc_4.2.2.149/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.2.149/include/IAgoraRtcEngine.h
headers/rtc_4.2.2.149/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.2.149/include/IAgoraSpatialAudio.h
headers/rtc_4.2.2.149/include/IAudioDeviceManager.h
headers/rtc_4.2.2.149/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.2.149_29293_FULL_20250622_0354_756380.zip

[AUTO] Update native headers to rtc_4.2.2.149

---

headers/rtc_4.2.6.203/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.203/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.203/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.203/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.203/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.203/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.203/include/AgoraBase.h
headers/rtc_4.2.6.203/include/AgoraMediaBase.h
headers/rtc_4.2.6.203/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.203/include/AgoraOptional.h
headers/rtc_4.2.6.203/include/AgoraRefPtr.h
headers/rtc_4.2.6.203/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.203/include/IAgoraLog.h
headers/rtc_4.2.6.203/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.203/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.203/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.203/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.203/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.203/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.203/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.203/include/IAgoraParameter.h
headers/rtc_4.2.6.203/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.203/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.203/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.203/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.203/include/IAudioDeviceManager.h
headers/rtc_4.2.6.203/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.203_headers.zip

[AUTO] Update native headers to rtc_4.2.6.203

---

headers/rtc_4.2.6.165/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.165/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.165/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.165/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.165/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.165/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.165/include/AgoraBase.h
headers/rtc_4.2.6.165/include/AgoraMediaBase.h
headers/rtc_4.2.6.165/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.165/include/AgoraOptional.h
headers/rtc_4.2.6.165/include/AgoraRefPtr.h
headers/rtc_4.2.6.165/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.165/include/IAgoraLog.h
headers/rtc_4.2.6.165/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.165/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.165/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.165/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.165/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.165/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.165/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.165/include/IAgoraParameter.h
headers/rtc_4.2.6.165/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.165/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.165/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.165/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.165/include/IAudioDeviceManager.h
headers/rtc_4.2.6.165/include/time_utils.h

https://download.agora.io/sdk/release/AgoraRtcEngine_windows_Preview_rtc_4.2.6.165_headers.zip

[AUTO] Update native headers to rtc_4.2.6.165

---

headers/rtc_4.2.6.164/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.164/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.164/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.164/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.164/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.164/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.164/include/AgoraBase.h
headers/rtc_4.2.6.164/include/AgoraMediaBase.h
headers/rtc_4.2.6.164/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.164/include/AgoraOptional.h
headers/rtc_4.2.6.164/include/AgoraRefPtr.h
headers/rtc_4.2.6.164/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.164/include/IAgoraLog.h
headers/rtc_4.2.6.164/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.164/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.164/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.164/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.164/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.164/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.164/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.164/include/IAgoraParameter.h
headers/rtc_4.2.6.164/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.164/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.164/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.164/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.164/include/IAudioDeviceManager.h
headers/rtc_4.2.6.164/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.164_29715_FULL_20250804_2341_822394.zip

[AUTO] Update native headers to rtc_4.2.6.164

---

headers/rtc_4.2.6.204/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.2.6.204/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.2.6.204/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.2.6.204/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.2.6.204/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.2.6.204/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.2.6.204/include/AgoraBase.h
headers/rtc_4.2.6.204/include/AgoraMediaBase.h
headers/rtc_4.2.6.204/include/AgoraMediaPlayerTypes.h
headers/rtc_4.2.6.204/include/AgoraOptional.h
headers/rtc_4.2.6.204/include/AgoraRefPtr.h
headers/rtc_4.2.6.204/include/IAgoraH265Transcoder.h
headers/rtc_4.2.6.204/include/IAgoraLog.h
headers/rtc_4.2.6.204/include/IAgoraMediaComponentFactory.h
headers/rtc_4.2.6.204/include/IAgoraMediaEngine.h
headers/rtc_4.2.6.204/include/IAgoraMediaPlayer.h
headers/rtc_4.2.6.204/include/IAgoraMediaPlayerSource.h
headers/rtc_4.2.6.204/include/IAgoraMediaRecorder.h
headers/rtc_4.2.6.204/include/IAgoraMediaStreamingSource.h
headers/rtc_4.2.6.204/include/IAgoraMusicContentCenter.h
headers/rtc_4.2.6.204/include/IAgoraParameter.h
headers/rtc_4.2.6.204/include/IAgoraRhythmPlayer.h
headers/rtc_4.2.6.204/include/IAgoraRtcEngine.h
headers/rtc_4.2.6.204/include/IAgoraRtcEngineEx.h
headers/rtc_4.2.6.204/include/IAgoraSpatialAudio.h
headers/rtc_4.2.6.204/include/IAudioDeviceManager.h
headers/rtc_4.2.6.204/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.2.6.204_29736_FULL_20250805_2016_823750.zip

[AUTO] Update native headers to rtc_4.2.6.204

---

headers/rtc_4.3.2.150/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.150/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.150/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.150/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.150/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.150/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.150/include/AgoraBase.h
headers/rtc_4.3.2.150/include/AgoraMediaBase.h
headers/rtc_4.3.2.150/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.150/include/AgoraOptional.h
headers/rtc_4.3.2.150/include/AgoraRefPtr.h
headers/rtc_4.3.2.150/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.150/include/IAgoraLog.h
headers/rtc_4.3.2.150/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.150/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.150/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.150/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.150/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.150/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.150/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.150/include/IAgoraParameter.h
headers/rtc_4.3.2.150/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.150/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.150/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.150/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.150/include/IAudioDeviceManager.h
headers/rtc_4.3.2.150/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.150_29540_FULL_20250721_1524_800257.zip

[AUTO] Update native headers to rtc_4.3.2.150

---

headers/rtc_4.3.2.17/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.17/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.17/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.17/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.17/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.17/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.17/include/AgoraBase.h
headers/rtc_4.3.2.17/include/AgoraMediaBase.h
headers/rtc_4.3.2.17/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.17/include/AgoraOptional.h
headers/rtc_4.3.2.17/include/AgoraRefPtr.h
headers/rtc_4.3.2.17/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.17/include/IAgoraLog.h
headers/rtc_4.3.2.17/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.17/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.17/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.17/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.17/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.17/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.17/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.17/include/IAgoraParameter.h
headers/rtc_4.3.2.17/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.17/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.17/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.17/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.17/include/IAudioDeviceManager.h
headers/rtc_4.3.2.17/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.17_29971_FULL_20250827_1443_857508.zip

[AUTO] Update native headers to rtc_4.3.2.17

---

headers/rtc_4.3.2.156/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.156/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.156/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.156/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.156/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.156/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.156/include/AgoraBase.h
headers/rtc_4.3.2.156/include/AgoraMediaBase.h
headers/rtc_4.3.2.156/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.156/include/AgoraOptional.h
headers/rtc_4.3.2.156/include/AgoraRefPtr.h
headers/rtc_4.3.2.156/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.156/include/IAgoraLog.h
headers/rtc_4.3.2.156/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.156/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.156/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.156/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.156/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.156/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.156/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.156/include/IAgoraParameter.h
headers/rtc_4.3.2.156/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.156/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.156/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.156/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.156/include/IAudioDeviceManager.h
headers/rtc_4.3.2.156/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.156_30176_FULL_20250920_1017_892809.zip

[AUTO] Update native headers to rtc_4.3.2.156

---

headers/rtc_4.3.2.157/custom_headers/CustomIAgoraMediaEngine.h
headers/rtc_4.3.2.157/custom_headers/CustomIAgoraMediaPlayer.h
headers/rtc_4.3.2.157/custom_headers/CustomIAgoraMusicContentCenter.h
headers/rtc_4.3.2.157/custom_headers/CustomIAgoraRtcEngine.h
headers/rtc_4.3.2.157/custom_headers/CustomIAgoraRtcEngineEx.h
headers/rtc_4.3.2.157/custom_headers/CustomIAudioDeviceManager.h
headers/rtc_4.3.2.157/include/AgoraBase.h
headers/rtc_4.3.2.157/include/AgoraMediaBase.h
headers/rtc_4.3.2.157/include/AgoraMediaPlayerTypes.h
headers/rtc_4.3.2.157/include/AgoraOptional.h
headers/rtc_4.3.2.157/include/AgoraRefPtr.h
headers/rtc_4.3.2.157/include/IAgoraH265Transcoder.h
headers/rtc_4.3.2.157/include/IAgoraLog.h
headers/rtc_4.3.2.157/include/IAgoraMediaComponentFactory.h
headers/rtc_4.3.2.157/include/IAgoraMediaEngine.h
headers/rtc_4.3.2.157/include/IAgoraMediaPlayer.h
headers/rtc_4.3.2.157/include/IAgoraMediaPlayerSource.h
headers/rtc_4.3.2.157/include/IAgoraMediaRecorder.h
headers/rtc_4.3.2.157/include/IAgoraMediaStreamingSource.h
headers/rtc_4.3.2.157/include/IAgoraMusicContentCenter.h
headers/rtc_4.3.2.157/include/IAgoraParameter.h
headers/rtc_4.3.2.157/include/IAgoraRhythmPlayer.h
headers/rtc_4.3.2.157/include/IAgoraRtcEngine.h
headers/rtc_4.3.2.157/include/IAgoraRtcEngineEx.h
headers/rtc_4.3.2.157/include/IAgoraSpatialAudio.h
headers/rtc_4.3.2.157/include/IAudioDeviceManager.h
headers/rtc_4.3.2.157/include/time_utils.h

https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_rel.v4.3.2.156_30176_FULL_20250920_1017_892809.zip

[AUTO] Update native headers to rtc_4.3.2.157
